# Generated by Django 3.2.7 on 2022-02-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_airbnblistings_listing_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AirbnbListings',
            new_name='AugmentedAirbnbListings',
        ),
    ]
