# Generated by Django 3.2.7 on 2022-02-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20220225_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airbnblistings',
            name='geom',
        ),
    ]
