# Generated by Django 3.2.7 on 2022-02-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_remove_airbnblistings_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airbnblistings',
            name='listing_number',
        ),
    ]
