# Generated by Django 3.2.7 on 2022-02-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_remove_airbnblistings_listing_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='airbnblistings',
            name='days_rented',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airbnblistings',
            name='dist_duomo',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airbnblistings',
            name='global_total_listings',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airbnblistings',
            name='has_liscense',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airbnblistings',
            name='host_florence',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airbnblistings',
            name='is_entire',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airbnblistings',
            name='is_hotel',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airbnblistings',
            name='is_instant_bookable',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airbnblistings',
            name='many_listings',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airbnblistings',
            name='only_1_listing',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airbnblistings',
            name='only_2_listings',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airbnblistings',
            name='rounded_revenue',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
