# Generated by Django 3.2.7 on 2022-02-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20220228_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='airbnblistings',
            name='listing_number',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
