# Generated by Django 3.2.7 on 2022-02-28 11:47

from django.db import migrations, models
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_auto_20220228_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirbnbListings',
            fields=[
                ('listing_number', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('listing_url', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('host_id', models.IntegerField()),
                ('host_name', models.CharField(max_length=1000)),
                ('host_since', models.CharField(max_length=100)),
                ('host_location', models.CharField(max_length=100)),
                ('host_total_listings_count', models.IntegerField()),
                ('neighbourhood_cleansed', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('room_type', models.CharField(max_length=100)),
                ('accommodates', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('price', models.FloatField()),
                ('availability_30', models.IntegerField()),
                ('availability_60', models.IntegerField()),
                ('availability_90', models.IntegerField()),
                ('availability_365', models.IntegerField()),
                ('number_of_reviews_ltm', models.IntegerField()),
                ('number_of_reviews_l30d', models.IntegerField()),
                ('license', models.CharField(max_length=100)),
                ('instant_bookable', models.CharField(max_length=10)),
                ('calculated_host_listings_count', models.IntegerField()),
                ('reviews_per_month', models.FloatField()),
                ('days_rented', models.FloatField()),
                ('rounded_revenue', models.FloatField()),
                ('is_hotel', models.IntegerField()),
                ('is_entire', models.IntegerField()),
                ('many_listings', models.IntegerField()),
                ('only_1_listing', models.IntegerField()),
                ('only_2_listings', models.IntegerField()),
                ('host_florence', models.IntegerField()),
                ('has_liscense', models.IntegerField()),
                ('is_instant_bookable', models.IntegerField()),
                ('global_total_listings', models.IntegerField()),
                ('dist_duomo', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='AugmentedAirbnbListings',
        ),
    ]
