# Generated by Django 3.2.7 on 2022-03-07 14:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_airbnblistings_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbnblistings',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
