# Generated by Django 3.2.7 on 2022-02-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_rename_airbnblistings_augmentedairbnblistings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='augmentedairbnblistings',
            name='listing_number',
        ),
        migrations.AddField(
            model_name='augmentedairbnblistings',
            name='field_1',
            field=models.CharField(default=0.0, max_length=10),
            preserve_default=False,
        ),
    ]
