# Generated by Django 3.2.7 on 2022-03-07 14:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_auto_20220228_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='airbnblistings',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default='0101000000000000000000F03F000000000000F03F', srid=4326),
            preserve_default=False,
        ),
    ]
