# Generated by Django 3.2.7 on 2022-05-15 10:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0012_auto_20220514_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbnblistings',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='geo'),
        ),
    ]
