# Generated by Django 3.2.7 on 2022-05-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0013_alter_airbnblistings_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbnblistings',
            name='host_location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='airbnblistings',
            name='host_since',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='airbnblistings',
            name='instant_bookable',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='airbnblistings',
            name='license',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='airbnblistings',
            name='neighbourhood_cleansed',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='airbnblistings',
            name='room_type',
            field=models.CharField(max_length=1000),
        ),
    ]
