# Generated by Django 3.2.7 on 2022-05-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0015_rename_airbnblistings_airbnblistingstable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AirbnbListingstable',
            new_name='AirbnbListings',
        ),
    ]
